project:
  type: book
  preview:
    port: 1810

book:
  title: Policy, Health Economics, and Psychological Resilience
  author:
    - name: "Aly Lamuri"
      affiliation:
        - Rijksuniversiteit Groningen
        - Universitas Indonesia
  sharing: [twitter, linkedin]
  back-to-top-navigation: true
  downloads: pdf
  output-file: journey
  date: last-modified
  license: "CC BY"
  comments:
    hypothesis:
      theme: clean
      openSidebar: false
      showHighlights: always
      usernameUrl: https://hypothes.is/users/lamurian
    giscus:
      repo: diographer/diographer.github.io
      theme: noborder_dark

website:
  back-to-top-navigation: true
  comments:
    hypothesis:
      theme: classic
      openSidebar: false
      showHighlights: always
      usernameUrl: https://hypothes.is/users/lamurian
    giscus:
      repo: diographer/diographer.github.io
      theme: noborder_dark
      input-position: top

profile:
  default: site

bibliography: ref.bib
knitr:
  opts_chunk:
    echo: false
    eval: true
    error: false
    message: false
    warning: false
    fig.width: 10
    fig.height: 8
    out.width: "\\textwidth"
    comment: "|"

execute:
  freeze: auto
