project:
  type: website
  output-dir: _render/site
  preview:
    port: 1810

website:
  search:
    type: textbox
    copy-button: true
    location: sidebar
  sidebar:
    title: "Policy and Resilience"
    style: docked
    alignment: right
    contents:
      - section: qmd/proposal/index.qmd
        contents:
          - text: Introduction
            href: qmd/proposal/intro.qmd
          - text: Literature Review
            href: qmd/proposal/litrev.qmd
          - text: Research Framework
            href: qmd/proposal/research-framework.qmd
          - text: Methods
            href: qmd/proposal/methods.qmd
          - text: Summary
            href: qmd/proposal/summary.qmd
      - section: qmd/learning-space/index.qmd
        contents:
          - text: Graph Theory
            href: qmd/learning-space/graph-theory.qmd
      - text: "About"
        href: qmd/about.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    toc-title: Contents
    page-layout: article
    grid:
      sidebar-width: 300px
      body-width: 1200px
      margin-width: 600px
    toc: true
