# Adapted from https://quarto.org/docs/publishing/github-pages.html
on:
  workflow_dispatch:
  push:
    branches: master

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@latest

      # Render and publish only index.qmd
      - name: Render and publish index.qmd
        run: quarto publish gh-pages index.qmd --no-prompt --no-browser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
